### PR TITLE
fix: remove blFooterShowGuestbook variable

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by DanielRuf** [comment]
Also see https://bugs.oxid-esales.com/view.php?id=6696#bugnotes

**Comment by Sieg** [comment]
Hi @DanielRuf! Thank you for your pull request! But i need to ask you to change it a little - I suggest to put it as migration in the eshop, as those demodata files are basically prepared after installing the shop on our demodata servers and dumping the database with some more additional steps. So we will lose the changes if we will merge it here.

**Comment by DanielRuf** [comment]
Can you show me the needed steps to create a migration with the right commands?

**Comment by DanielRuf** [comment]
Because obviously there are none and when I use the composer create-project commands I directly get this imported.

**Comment by Sieg** [comment]
Hi @DanielRuf, please check this article: https://docs.oxid-esales.com/developer/en/6.1/oxid_components/migrations.html

**Comment by DanielRuf** [comment]
It's too specific imho. Not sure how I can go from there to the needed result. In general it just affects the demo install at the moment. So why can we not do this here?

According to https://bugs.oxid-esales.com/view.php?id=6696#bugnotes it was fixed in 2017 and there is no info how it was fixed.

It seems the demoshop just imports this big SQL.

**Pull request closed without merging**
